ForbidCheckedExceptionInYieldingMethodRule: ignore implicit throw points
shipmonk-rnd/phpstan-rules pull request #114
Opened 2023-05-09 13:05 UTC by JanTvrdik

2023-05-09 14:34 UTC, janedbal requested changes
Can you reproduce that error in https://github.com/shipmonk-rnd/input-mapper/pull/2 in the testcase here? The fix seems ok, but I'd like the test to fail if I drop that new condition.

2023-05-09 14:47 UTC, JanTvrdik commented
I updated the test to mark `Throwable` exception as checked. It does not make a lot of sense, but it reproduces the issue.

2023-05-09 14:52 UTC, janedbal commented
>  updated the test to mark Throwable exception as checked

But there is no such thing in https://github.com/shipmonk-rnd/input-mapper/blob/master/phpstan.neon.dist

2023-05-09 14:57 UTC, JanTvrdik commented
I guess it's the default phpstan behavior if checkedExceptionClasses is not explicitly configured.

2023-05-15 07:20 UTC, janedbal approved these changes

2023-05-15 10:33 UTC, merged